# CURSO INTENSIVO DE INTRODUCCIÓN AL ÁLGEBRA LINEAL

In [1]:
import numpy as np

## INTRODUCCIÓN AL ÁLGEBRA LINEAL

Como decíamos al principio muchos de los algoritmos de machine learning se construyen con operaciones avanzadas sobre estructuras de datos como vectores o matrices.

Realmente no es necesario un conocimiento profundo de álgebra para hacer machine learning. Pero si es interesante por lo menos tener una nociones de lo que está pasando por debajo.

Y de nuevo el paquete base para hacer todo esto es Numpy, que seguiremos utilizando durante esta explicación.

**Un poco de teoría: profundizando en la comprensión de las estructuras de datos**

Hasta ahora hemos visto 3 estructuras:

* Escalares: en la lección de Python los llamábamos "datos individuales"
* Vectores: secuencias de varios escalares
* Matrices: secuencias de varios vectores organizados en dos dimensiones

Geométricamente los escalares son simplemente un punto y se dice que tienen dimensión cero.

Los vectores son una recta y tienen dimensión 1. De hecho pueden ser representados como matrices de dimensión 1, por ej m x 1 si son verticales o 1 x m si son horizontales.

Las matrices son un plano, y tienen dimensión 2, que se denota por m x n.

Y podemos seguir extendiendo a los arrays multidimensionales, que son hiperplanos con dimensión n.

In [2]:
#Ejemplo de escalar con Numpy
np.array(1)

array(1)

In [3]:
#Ejemplo de vector con Numpy
np.array([1,2,3])

array([1, 2, 3])

In [4]:
#Ejemplo de matriz con Numpy
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#Ejemplo de array multidimensional con Numpy
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### OPERACIONES CON VECTORES

#### SUMAR VECTORES

La condición es que tienen que tener la misma longitud

In [6]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

v1 + v2

array([5, 7, 9])

#### RESTAR VECTORES

La condición es que tienen que tener la misma longitud

In [7]:
v1 - v2

array([-3, -3, -3])

#### MULTIPLICAR UN VECTOR POR UN ESCALAR

In [8]:
v1 * 10

array([10, 20, 30])

#### MULTIPLICAR DOS VECTORES

La condición es que tienen que tener la misma longitud

El tipo de multiplicación más usado es el producto escalar o punto producto: multiplicar uno a uno los correspondientes y luego sumar los resultados.

In [9]:
v1

array([1, 2, 3])

In [10]:
v2

array([4, 5, 6])

In [11]:
np.dot(v1,v2)

32

### OPERACIONES CON MATRICES

In [13]:
v3d = np.array([[[ 3, -4,  6],[ 0, -8,  3]],
             [[ 6, 5,  -4],[ 9, -1,  -2]]])
v3d

array([[[ 3, -4,  6],
        [ 0, -8,  3]],

       [[ 6,  5, -4],
        [ 9, -1, -2]]])

In [15]:
v3d[0,1,1]

-8

#### SUMAR MATRICES

La condición es que tienen que tener la misma forma

In [16]:
m1 = np.array([[ 3, -4,  6],[ 0, -8,  3]])
m2 = np.array([[ -1, -9,  7],[ 4, 8,  -7]])

m1 + m2

array([[  2, -13,  13],
       [  4,   0,  -4]])

#### RESTAR MATRICES

La condición es que tienen que tener la misma forma

In [17]:
m1 - m2

array([[  4,   5,  -1],
       [ -4, -16,  10]])

#### MULTIPLICAR UNA MATRIZ POR UN ESCALAR

In [18]:
m1 * 10

array([[ 30, -40,  60],
       [  0, -80,  30]])

#### MULTIPLICAR DOS MATRICES

Usaremos la forma del punto producto.

La condición es que el número de columnas de la primera tiene que ser el mismo que el número de filas de la segunda.

Más formalmente es multiplicar una m x n por una n x k.

Por ejemplo multiplicar una 3x2 por una 2x4.

Es así porque lo que hace el punto producto es ir multiplicando cada fila de la primera por cada columna de la segunda.

El resultado será una nueva matriz de m x k, ej 3x4.

Donde el puntoproducto de fila1 de la primera por columna 1 de la segunda será el resultado de la fila1,columna1 de la tercera.

In [19]:
# Veamos la dimensión de m1
m1.shape

(2, 3)

In [20]:
m1

array([[ 3, -4,  6],
       [ 0, -8,  3]])

In [21]:
# Y creemos por ejemplo otra matriz 3x3
m3 = np.array([
    [8,6,2],
    [6,3,4],
    [2,-4,6]
])
m3.shape

(3, 3)

In [22]:
#Hacemos la multiplicación punto producto igual que con los vectores
np.dot(m1,m3)

array([[ 12, -18,  26],
       [-42, -36, -14]])

#### APLANAR UNA MATRIZ

Habrá ocasiones en machine learning que aunque tengamos que usar una matriz el formato en el que tenemos que pasarle esa matriz a la clase que la procesará es un array unidimensional.

Aplanar una matriz (flatten en inglés) significa eso, pasarla de dimensión 2 a dimensión 1, simplemente concatenando todas sus filas en una sola.

Lo hacemos con el método flatten de Numpy.

In [23]:
#Recordemos como es la matriz m3
m3

array([[ 8,  6,  2],
       [ 6,  3,  4],
       [ 2, -4,  6]])

In [24]:
#Así queda al aplanarla
m3.flatten()

array([ 8,  6,  2,  6,  3,  4,  2, -4,  6])

### PARA QUÉ SIRVE TODO ESTO

Muchas de las operaciones en ML se pueden hacer mediante álgebra matricial.

Y de hecho hacerlas asi es más eficiente computacionalmente.

Por lo que los algoritmos ya las hacen asi aunque nosotros no seamos conscientes ni tengamos que hacer nada al respecto.

**Deep learning:**

Deep learning es un subcampo de machine learning basado en la evolución de un algoritmo concreto llamado redes neuronales.

Es un campo en si mismo, bastante complejo y que solo se debe abordar una vez que se tengan muy trabajadas las bases generales de todo lo que vemos en este programa. Por tanto no entraremos en él.

Pero si más o menos estás en el ámbito seguro que has oído hablar por ejemplo de TensorFlow (el framework de deep learning de Google).

Pues bien, se llama así porque los tensores son la base de deep learning.

Pero realmente los tensores no son más que la generalización de lo que hemo visto:

* Un escalar es un tensor de rango 0
* Un vector es un tensor de rango 1
* Una matriz es un tensor de rango 2
* Puede haber tensores de muchas más dimensiones, por ej uno de rango 3 sería una colección de matrices

En Python los tensores se gestionan con nd.arrays.

In [25]:
# Ejemplo de tensor de rango 3

m1 = np.array([[ 3, -4,  6],[ 0, -8,  3]])
m2 = np.array([[ -1, -9,  7],[ 4, 8,  -7]])

tensor = np.array([m1,m2])
tensor

array([[[ 3, -4,  6],
        [ 0, -8,  3]],

       [[-1, -9,  7],
        [ 4,  8, -7]]])

In [26]:
# También se podría haber creado directamente así

tensor = np.array([[[ 3, -4,  6],[ 0, -8,  3]],[[ -1, -9,  7],[ 4, 8,  -7]]])
tensor

array([[[ 3, -4,  6],
        [ 0, -8,  3]],

       [[-1, -9,  7],
        [ 4,  8, -7]]])

In [27]:
# Vemos que retorna una colección de 2 matrices cada una de 2x3
tensor.shape

(2, 2, 3)

Pongamos el ejemplo de **Computer Vision:**

Especialmente en Deep Learning se trabaja mucho con imágenes. Pero un ordenador no ve las imágenes como nosotros.

Cada imagen es en realidad un conjunto de pixeles, por ej de 1000x1000, es decir una matriz, o un tensor de rango 2.

En una imagen en blanco y negro cada celda sería un número entre 0 y 255 que denota la escala de gris. Siendo 0 blanco puro y 255 negro puro.

Una forma de incluir color es usar las escalas RGB, donde cualquier color se puede representar como una combinación de esos 3 colores.

Por tanto tendríamos una matriz de 1000x1000 por cada uno de esos 3 canales, es decir 1000x1000x3 o un tensor de rango 3.

Y así es como podemos representar una imagen con álgebra matricial y aplicarle machine learning.

Por ejemplo vamos a poner un caso simplificado donde la imagen fuera solo de 5x5 pixeles.

Usando una función de numpy para generar aleatorios entre 0 y 255 así es como el ordendador "vería" esa imagen.

In [28]:
R = np.random.randint(0,255,(5,5))
G = np.random.randint(0,255,(5,5))
B = np.random.randint(0,255,(5,5))

imagen = np.array([R,G,B])
imagen

array([[[156, 159, 252,   0,  57],
        [ 11,  25, 241, 220,  22],
        [147,   5, 245,  54,  19],
        [197, 176,  72, 139,  59],
        [ 26, 240,  37,  13,  14]],

       [[144,  38,  60, 162,   4],
        [ 97,  25,   0, 180,   7],
        [216, 187, 219,  41,  81],
        [151,  10, 240,   7, 194],
        [212, 181, 127,   0, 198]],

       [[ 35, 180, 232, 172, 233],
        [  8,  61,  32,  13,  84],
        [144, 183, 228, 204,  13],
        [252, 245, 186,  88, 184],
        [143,  71, 100,  24,  33]]])

In [29]:
R = np.random.randint(0,255,(5,5))
R

array([[114, 241, 219, 148,  57],
       [ 44, 153,  16, 220, 172],
       [  1,   8, 174, 115,  83],
       [  0,  17,  81, 235,  82],
       [130,  72,  58,  42,  44]])

In [30]:
G = np.random.randint(0,255,(5,5))
G

array([[115, 173,  14, 227,  48],
       [221,  76, 111, 227, 247],
       [ 35,  59,  71,  93, 213],
       [132,  51, 151,  72, 190],
       [ 72, 250, 228, 211, 222]])

In [31]:
B = np.random.randint(0,255,(5,5))
B

array([[ 71,  18, 222, 155, 205],
       [170,  29, 252, 119, 139],
       [167, 123, 237, 170, 198],
       [ 36,  86, 254,  77, 219],
       [172,   5, 226,  89, 222]])

## PARA SABER MÁS

Como lectura complementaria (y voluntaria no necesaria) para consolidar y complementar lo que hemos aprendido te recomiendo el siguiente post:

https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d

En el cual se refuerzan estos conceptos de una forma muy gráfica que puede ayudar a su consolidación.